"""empty message

Revision ID: cd44522203e6
Revises: 0b2aa96179b4
Create Date: 2018-05-07 14:36:18.035986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd44522203e6'
down_revision = '0b2aa96179b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'guid')
    # ### end Alembic commands ###
